[package]
name = "gcd"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]


[dev-dependencies]
num-integer = "0.1.45"
rand = "0.8.5"
primes = "0.3.0"